services:
  - type: web
    name: financas-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma migrate deploy && npx prisma generate
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /api/health